server:
  PORT: 80

audiobooks:
  DATA_DIR: "/home/memi/projects/bookplayer/data"
  INTERVAL: 5m

prcocessd:
  PROCESSED_DIR: "/home/memi/projects/bookplayer/processed"

db:
  DATA_SOURCE: "/home/memi/projects/bookplayer/backend/local.db"
  DRIVER: "sqlite3"