// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package datasource

type Audiobook struct {
	ID           int64
	Title        string
	Author       string
	Narrator     string
	Description  string
	Duration     int64
	DirPath      string
	ChapterCount int64
	Genre        string
}

type Chapter struct {
	ID          int64
	AudiobookID int64
	Numbering   int64
	Title       string
	StartTime   float64
	EndTime     float64
	FilePath    string
}
